name: "Test Config File"
description: "This should be excluded from batch execution"
variables:
  CONFIG_TYPE: "test"
  
steps:
  - name: "Config test step"
    args:
      Command: "NOOP"
      Type: "CONFIG"
    test:
      - "CONFIG_TYPE exists"

options:
  timeout: 10000